# fly.toml app configuration file generated for dan-mac-ai-podcast-weekly on 2025-02-24T03:54:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dan-mac-ai-podcast-weekly'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
